import { Nav } from "@/components/nav"
import { Footer } from "@/components/sections/footer"
import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Artifacts - Kaname",
  description:
    "Four structured markdown files form the Kaname artifact chain. Each governs the one that follows it. constitution.md is the highest authority.",
}

const artifacts = [
  {
    file: "constitution.md",
    owner: "Constitution Guardian",
    commitment: "Technical Contract",
    index: "01",
    description:
      "The constitution defines the non-negotiable boundaries of the system: architectural decisions, approved technology constraints, security requirements, and quality standards. It is the highest authority in Kaname. All other artifacts and all AI-generated output must conform to it.",
    completeness:
      "The constitution is complete when every constraint it contains is verifiable and when a reviewer can assess any AI-generated output against it without ambiguity.",
    governs: "spec.md",
  },
  {
    file: "spec.md",
    owner: "Spec Owner",
    commitment: "Behavioral Intent",
    index: "02",
    description:
      "The specification defines system behavior from the user's perspective. It is organized as System Use Cases - each describing one meaningful interaction between an actor and the system, including all successful paths, variants, and failure conditions. As systems grow, teams may organize the specification across multiple documents by domain or Epic. The artifact is the totality of Use Case specifications, regardless of physical structure.",
    completeness:
      "The specification is complete when a Task Implementer can execute any Use Case using an AI agent without requesting clarification, and when every acceptance criterion is independently verifiable by a human reviewer. A Use Case that meets this standard is Spec-Ready.",
    governs: "plan.md",
  },
  {
    file: "plan.md",
    owner: "Plan Reviewer",
    commitment: "Architecture Alignment",
    index: "03",
    description:
      "The plan describes the technical architecture for implementing the specification. It includes the component structure, data model, API contracts, and implementation sequence. The plan is generated by an AI agent from the specification and reviewed by the Plan Reviewer.",
    completeness:
      "The plan is complete when every Use Case in scope for the current delivery cycle maps to a defined technical component, no implementation decision contradicts the constitution, and the sequence is feasible given known dependencies.",
    governs: "tasks.md",
  },
  {
    file: "tasks.md",
    owner: "Task Implementer",
    commitment: "Implementation Completeness",
    index: "04",
    description:
      "The task breakdown translates the plan into discrete, executable units of work ordered for implementation. Each task maps to one Use Case and one plan component. Each task is self-contained: it carries the Use Case reference, relevant acceptance criteria, and plan component context sufficient for an AI agent to implement it without external clarification. Tasks are pulled by Task Implementers from the board as capacity allows.",
    completeness:
      "A task is complete when the AI-generated output satisfies its linked Use Case acceptance criteria and passes the Implementation Gate review.",
    governs: null,
  },
]

export default function ArtifactsPage() {
  return (
    <div className="min-h-screen bg-[#0f172a] text-slate-50">
      <Nav />

      {/* Hero */}
      <section className="px-6 py-20 md:px-16 md:py-28">
        <div className="mx-auto max-w-5xl">
          <p className="mb-4 text-[10px] font-semibold tracking-[4px] text-amber-400 uppercase">
            Kaname Artifacts
          </p>
          <h1 className="mb-6 text-5xl font-extrabold tracking-[-2px] text-slate-50 md:text-6xl">
            The Artifact Chain
          </h1>
          <p className="mb-4 max-w-xl text-base leading-relaxed text-slate-400">
            Four structured markdown files form a chain of constraint. Each
            artifact governs the one that follows it. constitution.md is the
            highest authority - nothing in the chain may contradict it.
          </p>
          <p className="max-w-xl text-sm leading-relaxed text-slate-500">
            Each artifact carries a commitment: a binding quality standard
            against which it is evaluated at its corresponding human gate.
            Ownership means accountability for quality and currency - not
            exclusive authorship.
          </p>
        </div>
      </section>

      {/* Chain visual */}
      <section className="border-t border-slate-800 bg-[#0a0f1e] px-6 py-12 md:px-16">
        <div className="mx-auto max-w-5xl">
          <p className="mb-8 text-[10px] font-semibold tracking-[3px] text-slate-600 uppercase">
            Chain of Constraint
          </p>
          <div className="space-y-0">
            {artifacts.map((a) => (
              <div key={a.file}>
                <div className="flex items-center gap-4 rounded-lg border border-slate-800 bg-[#0f172a] px-5 py-4">
                  <code className="shrink-0 font-mono text-sm font-bold text-amber-400">
                    {a.file}
                  </code>
                  <span className="hidden text-slate-800 md:block">·</span>
                  <span className="hidden text-[11px] text-slate-600 md:block">
                    {a.owner}
                  </span>
                  <span className="ml-auto text-[9px] font-semibold tracking-[2px] text-amber-400/50 uppercase">
                    {a.commitment}
                  </span>
                </div>
                {a.governs && (
                  <div className="flex items-center gap-3 px-5 py-2 text-slate-700">
                    <div className="h-5 w-px bg-slate-800" />
                    <span className="text-[9px] tracking-[3px] uppercase">
                      governs
                    </span>
                    <svg
                      width="10"
                      height="10"
                      viewBox="0 0 10 10"
                      fill="none"
                      className="text-slate-700"
                    >
                      <path
                        d="M5 0v8M2 5l3 4 3-4"
                        stroke="currentColor"
                        strokeWidth="1.5"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      />
                    </svg>
                  </div>
                )}
              </div>
            ))}
          </div>
          <p className="mt-6 text-[10px] text-slate-500">
            AI-generated output at every stage must conform to constitution.md.
            A violation at any level is a constitutional violation.
          </p>
        </div>
      </section>

      {/* Artifact deep-dives */}
      <div className="border-t border-slate-800">
        {artifacts.map((a, i) => (
          <section
            key={a.file}
            className={`border-b border-slate-800 px-6 py-16 md:px-16 md:py-20 ${
              i % 2 === 1 ? "bg-[#0a0f1e]" : ""
            }`}
          >
            <div className="mx-auto max-w-5xl">
              {/* Header */}
              <div className="mb-8 flex flex-wrap items-baseline gap-4">
                <span className="font-mono text-xs font-semibold tracking-widest text-amber-400/50">
                  {a.index}
                </span>
                <code className="text-2xl font-bold tracking-tight text-amber-400 md:text-3xl">
                  {a.file}
                </code>
              </div>

              {/* Commitment + Owner */}
              <div className="mb-8 flex flex-wrap gap-3">
                <span className="rounded border border-amber-400/20 bg-amber-950/20 px-3 py-1 text-[10px] font-semibold tracking-[2px] text-amber-400/80 uppercase">
                  {a.commitment}
                </span>
                <span className="rounded border border-slate-800 px-3 py-1 text-[10px] text-slate-500">
                  Owner: {a.owner}
                </span>
              </div>

              {/* Description */}
              <blockquote className="mb-10 border-l-2 border-amber-400 pl-6">
                <p className="text-base leading-relaxed text-slate-300">
                  {a.description}
                </p>
              </blockquote>

              {/* Completeness */}
              <div className="rounded-lg border border-slate-800 bg-[#0a0f1e] p-5">
                <p className="mb-2 text-[11px] font-semibold tracking-[2px] text-slate-500 uppercase">
                  Commitment: when is it complete?
                </p>
                <p className="text-sm leading-relaxed text-slate-400">
                  {a.completeness}
                </p>
              </div>

              {/* Governs */}
              {a.governs && (
                <p className="mt-6 text-[11px] text-slate-600">
                  Governs:{" "}
                  <code className="text-amber-400/60">{a.governs}</code>
                </p>
              )}
              {!a.governs && (
                <p className="mt-6 text-[11px] text-slate-600">
                  Terminal artifact - governs AI-generated implementation directly.
                </p>
              )}
            </div>
          </section>
        ))}
      </div>

      {/* Ownership note */}
      <section className="border-t border-slate-800 bg-[#0a0f1e] px-6 py-14 md:px-16">
        <div className="mx-auto max-w-5xl">
          <div className="grid gap-4 md:grid-cols-2">
            <div className="rounded-lg border border-slate-800 bg-[#0f172a] p-5">
              <p className="mb-2 text-[11px] font-semibold tracking-[2px] text-slate-500 uppercase">
                Ownership
              </p>
              <p className="text-sm leading-relaxed text-slate-400">
                Each artifact has a designated owner. Ownership means
                accountability for quality and currency - not exclusive
                authorship. Others may contribute. The owner is accountable
                for the artifact meeting its commitment.
              </p>
            </div>
            <div className="rounded-lg border border-red-900/30 bg-red-950/20 p-5">
              <p className="mb-2 text-[11px] font-semibold tracking-[2px] text-red-400/70 uppercase">
                Unassigned artifacts
              </p>
              <p className="text-sm leading-relaxed text-slate-400">
                If any artifact lacks a named owner, the team is not running
                Kaname. Accountability may not go unassigned. One person may
                hold multiple roles - but each artifact must have a name
                attached to it.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="border-t border-slate-800 px-6 py-16 md:px-16">
        <div className="mx-auto flex max-w-5xl flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
          <p className="text-sm text-slate-500">
            Each artifact is evaluated at a human gate before work advances.
          </p>
          <div className="flex gap-3">
            <a
              href="/gates"
              className="rounded border border-slate-800 px-4 py-2 text-[10px] tracking-widest text-slate-500 uppercase transition-colors hover:border-slate-600 hover:text-slate-300"
            >
              Human Gates
            </a>
            <a
              href="/kaname-guide.pdf"
              download
              className="rounded bg-amber-400 px-4 py-2 text-[10px] font-bold tracking-widest text-[#0f172a] uppercase transition-colors hover:bg-amber-300"
            >
              ↓ Full Guide PDF
            </a>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  )
}
